"""Drop capability columns.

Tears down the capability abstraction's data plane:
  * `departments.capabilities`           (JSONB array of enabled keys)
  * `departments.capability_configs`     (per-capability JSONB config)
  * `department_templates.default_capabilities`
  * `department_templates.default_capability_configs`

Tab routing now lives in `frontend/src/features/projects/lib/projectTabs.ts`,
keyed by `department.template_key`. The schemas + service layer were updated
in the same PR so the DROP is safe.

The autogenerated diff also picked up incidental schema drift on unrelated
tables (denormalized `business_id` columns on per-capability tables,
constraint cosmetics on `businesses`, `department_stages`, `participants`,
and `user_notification_prefs`). Those are intentional and left alone — this
migration is focused.

Down-migration restores the columns as JSONB defaults; data is unrecoverable
but the schema round-trips.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d772f245fe78"
down_revision: str | Sequence[str] | None = "d5e8f2a9c1b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_column("departments", "capability_configs")
    op.drop_column("departments", "capabilities")
    op.drop_column("department_templates", "default_capability_configs")
    op.drop_column("department_templates", "default_capabilities")


def downgrade() -> None:
    op.add_column(
        "department_templates",
        sa.Column(
            "default_capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "department_templates",
        sa.Column(
            "default_capability_configs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "capability_configs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
